name: green
version: 0.1.0.0
git: https://bitsof.thisfieldwas.green/keywordsalad/thisfieldwas.green
license: BSD3
author: Logan McGrath
maintainer: "logan.mcgrath@thisfieldwas.green"
copyright: "Copyright (C) 2012-2021 Logan McGrath"

extra-source-files:
  - README.md

description: Please see the README at <https://bitsof.thisfieldwas.green/keywordsalad/thisfieldwas.green#readme>

dependencies:
  - base >= 4.14 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - directory
    - filepath
    - hakyll
    - hakyllbars
    - hjsmin
    - MissingH
    - microlens
    - microlens-th
    - mtl
    - optparse-applicative
    - pandoc
    - template-haskell
    - text
    - time
    - yaml

executables:
  site:
    main: Main.hs
    source-dirs: app/site
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - green
  author:
    main: Main.hs
    source-dirs: app/author
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - green

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - containers
      - green
      - hakyll
      - hspec
      - parsec
      - time

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - UndecidableInstances
  - ViewPatterns

ghc-options:
  - -fprint-potential-instances
  - -Wall
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-patterns
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wname-shadowing
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wunused-packages
  - -Wunused-type-patterns
