###############################################################################
jobs:
###############################################################################

# Build and test the site
- name: build-and-test-site
  max_in_flight: 1
  public: true
  interruptible: true
  plan:
  - get: site-prebaked-image
    trigger: true
  - get: site-repo
    trigger: true
  - task: build-and-test
    image: site-prebaked-image
    config:
      platform: linux
      inputs:
      - name: site-repo
      outputs:
      - name: site-build
      run:
        path: sh
        args:
        - -cx
        - |
          set -eux
          cd site-repo
          ./go build
          ./go test

# Create the docker image with the library dependencies pre-built
- name: site-prebaked-image-job
  max_in_flight: 1
  public: true
  interruptible: true
  plan:
  - get: site-prebaked-image-repo
    trigger: true
  - get: site-base-image
    trigger: true
  - get: site-repo
  - get: oci-build-task
  - task: build-image
    image: oci-build-task
    privileged: true
    config:
      platform: linux
      inputs:
      - name: site-prebaked-image-repo
      - name: site-repo
      outputs:
      - name: image
      params:
        DOCKERFILE: site-prebaked-image-repo/ci/prebaked-site/Dockerfile
        UNPACK_ROOTFS: true
      run:
        path: build
  - put: site-prebaked-image
    params:
      image: image/image.tar

# Create the base docker image
- name: site-base-image-job
  max_in_flight: 1
  public: true
  interruptible: true
  plan:
  - get: site-base-image-repo
    trigger: true
  - get: oci-build-task
  - task: build-image
    image: oci-build-task
    privileged: true
    config:
      platform: linux
      inputs:
      - name: site-base-image-repo
      outputs:
      - name: image
      params:
        DOCKERFILE: site-base-image-repo/ci/base-site/Dockerfile
        UNPACK_ROOTFS: true
      run:
        path: build
  - put: site-base-image
    params:
      image: image/image.tar

###############################################################################
resources:
###############################################################################

# Site source code
- name: site-repo
  type: git
  icon: git
  source:
    uri: https://bitsof.thisfieldwas.green/keywordsalad/thisfieldwas.green.git
    branch: main
    ignore_paths:
    - ci/*
    - package.yaml
    - stack.yaml

# Docker image with site library dependencies pre-built
- name: site-prebaked-image
  type: registry-image
  icon: docker
  source:
    repository: registry:5000/tfwg/prebaked-site
    tag: latest
    insecure: true
- name: site-prebaked-image-repo
  type: git
  icon: git
  source:
    uri: https://bitsof.thisfieldwas.green/keywordsalad/thisfieldwas.green.git
    branch: main
    paths:
    - ci/prebaked-site/*
    - package.yaml
    - stack.yaml

# Docker image with software dependencies installed
- name: site-base-image
  type: registry-image
  icon: docker
  source:
    repository: registry:5000/tfwg/base-site
    tag: latest
    insecure: true
- name: site-base-image-repo
  type: git
  icon: git
  source:
    uri: https://bitsof.thisfieldwas.green/keywordsalad/thisfieldwas.green.git
    branch: main
    paths:
    - ci/base-site/*

# Docker image used to create other docker images
- name: oci-build-task
  type: registry-image
  icon: docker
  source:
    repository: concourse/oci-build-task
